import React, { useEffect } from 'react';
import { X } from 'lucide-react';

/**
 * Full-screen system legal & regulatory disclosure overlay.
 * onClose only dismisses this layer — caller keeps parent route (e.g. Methodology) mounted.
 */
export default function SystemLegalPolicyOverlay({
  open,
  onClose,
  dismissHint = 'ESC · X · returns to previous screen',
}) {
  useEffect(() => {
    if (!open) return undefined;
    const onKeyDown = (event) => {
      if (event.key === 'Escape') onClose?.();
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[130] flex flex-col animate-fade-in"
      role="dialog"
      aria-modal="true"
      aria-labelledby="system-legal-policy-title"
    >
      <div aria-hidden="true" className="absolute inset-0 bg-slate-950/96 backdrop-blur-2xl" />

      <div className="relative flex flex-col w-full h-full min-h-0 overflow-hidden bg-slate-950 shadow-[inset_0_0_120px_rgba(255,102,0,0.06)]">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-orange-500/70 to-transparent"
        />

        <div className="relative shrink-0 flex items-center justify-between gap-4 border-b border-orange-900/40 bg-gradient-to-r from-orange-950/30 via-slate-950 to-slate-950 px-4 py-3 md:px-8 md:py-4">
          <div className="min-w-0 flex-1">
            <p className="text-[9px] md:text-[10px] font-mono text-orange-500/80 uppercase tracking-[0.35em] mb-1">
              // SYSTEM REGULATORY DATA ENVELOPE
            </p>
            <h2
              id="system-legal-policy-title"
              className="text-sm sm:text-base md:text-xl font-black text-orange-50 uppercase tracking-[0.05em] leading-tight"
            >
              View System Legal Policy
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="shrink-0 p-2 rounded-lg border border-slate-700 bg-slate-900/80 text-slate-400 hover:text-orange-300 hover:border-orange-600 transition-colors"
            aria-label="Close system legal policy"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 min-h-0 overflow-y-auto custom-scrollbar px-4 py-6 md:px-10 md:py-8">
          <div className="max-w-3xl mx-auto space-y-6">
            <section className="rounded-xl border border-orange-900/45 bg-slate-900/55 p-5 md:p-6">
              <p className="text-[11px] font-black uppercase tracking-[0.22em] text-orange-300 mb-4">
                Educational &amp; Fitness Use Disclosure
              </p>
              <p className="text-[13px] md:text-[14px] text-slate-200 leading-relaxed">
                The biometric telemetry tracking data generated by this platform is provided strictly for
                educational, fitness tracking, and movement optimization purposes. This system presents general
                structural information only and does not provide personalized medical advice, clinical
                diagnostics, or injury treatment protocols.
              </p>
            </section>

            <section className="rounded-xl border border-slate-800 bg-slate-950/80 p-5 md:p-6">
              <p className="text-[11px] font-black uppercase tracking-[0.22em] text-slate-400 mb-4">
                Safety &amp; Verification Protocol
              </p>
              <p className="text-[13px] text-slate-300 leading-relaxed">
                Always double-check physical setup dimensions to verify safety limits before performing any
                assessed movement pattern. Consult qualified medical or coaching professionals for injury,
                pain, or clinical concerns — this terminal does not replace licensed healthcare evaluation.
              </p>
            </section>

            <section className="rounded-xl border border-cyan-900/40 bg-cyan-950/10 p-5 md:p-6">
              <p className="text-[11px] font-black uppercase tracking-[0.22em] text-cyan-400 mb-4">
                Data Channel &amp; Local Processing
              </p>
              <p className="text-[13px] text-slate-300 leading-relaxed">
                Movement analysis pipelines may route through localhost development services during lab sessions.
                Secure terminal credentials and client dossier exports remain under coach-controlled archival
                policy. Unauthorized archive access is prohibited.
              </p>
            </section>

            <p className="text-[9px] text-slate-600 uppercase tracking-[0.25em] text-center pt-2">
              {dismissHint}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
